Resources:
  usersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.tableName}
      AttributeDefinitions:
        - AttributeName: userCategory
          AttributeType: S
        - AttributeName: userId
          AttributeType: S          
      KeySchema:
        - AttributeName: userCategory
          KeyType: HASH
        - AttributeName: userId
          KeyType: RANGE
      # Set the capacity based on the stage
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tableThroughput}
        WriteCapacityUnits: ${self:custom.tableThroughput}
